/** Каталог тестових товарів для seed (без старих демо-позицій). */
export type SeedProductRow = {
  name: string;
  slug: string;
  category: "Квіти" | "Кущі" | "Трави";
  price: number;
  stock: number;
  description: string;
  care: string;
  seoTitle: string;
  seoDescription: string;
};

export const SEED_PRODUCTS: SeedProductRow[] = [
  { name: "Троянда чайно гібридна Аваланж", slug: "trojanda-chajno-gibrydna-avalanzh", category: "Квіти", price: 249, stock: 18, description: "Елегантна біла троянда з великими бутонами для саду та зрізу.", care: "Сонячне місце, регулярний полив, обрізка навесні.", seoTitle: "Троянда Аваланж купити", seoDescription: "Купити білу чайно гібридну троянду Аваланж для саду." },
  { name: "Троянда Флорібунда Ніна", slug: "trojanda-floribunda-nina", category: "Квіти", price: 219, stock: 24, description: "Яскрава троянда з рясним цвітінням протягом сезону.", care: "Сонце, родючий ґрунт, помірний полив.", seoTitle: "Троянда Флорібунда Ніна", seoDescription: "Садова троянда Флорібунда Ніна з тривалим цвітінням." },
  { name: "Півонія Сара Бернар", slug: "pyvoniya-sara-bernar", category: "Квіти", price: 329, stock: 12, description: "Класична рожева півонія з великими ароматними квітами.", care: "Сонце або півтінь, полив без застою води.", seoTitle: "Півонія Сара Бернар", seoDescription: "Купити півонію Сара Бернар для декоративного саду." },
  { name: "Півонія Ред Шарм", slug: "pyvoniya-red-sharm", category: "Квіти", price: 359, stock: 10, description: "Насичено червона півонія з густими махровими квітами.", care: "Родючий ґрунт, сонячне місце, мульчування.", seoTitle: "Півонія Ред Шарм", seoDescription: "Червона півонія Ред Шарм для саду та клумб." },
  { name: "Лаванда вузьколиста Хідкот", slug: "lavanda-vuzkolysta-hidkot", category: "Квіти", price: 149, stock: 35, description: "Компактна лаванда з фіолетовими суцвіттями та приємним ароматом.", care: "Сонце, легкий ґрунт, мінімальний полив.", seoTitle: "Лаванда Хідкот", seoDescription: "Купити лаванду Хідкот для саду, бордюрів і кашпо." },
  { name: "Лаванда Мунстед", slug: "lavanda-munsted", category: "Квіти", price: 139, stock: 40, description: "Невибаглива ароматна лаванда для сонячних ділянок.", care: "Сухий ґрунт, багато світла, обрізка після цвітіння.", seoTitle: "Лаванда Мунстед", seoDescription: "Ароматна лаванда Мунстед для ландшафтного дизайну." },
  { name: "Ехінацея Пурпурова", slug: "ehinatseya-purpurova", category: "Квіти", price: 159, stock: 28, description: "Багаторічна квітка з великими пурпуровими суцвіттями.", care: "Сонце, помірний полив, видалення сухих квітів.", seoTitle: "Ехінацея Пурпурова", seoDescription: "Купити ехінацею пурпурову для квітника." },
  { name: "Ехінацея Вайт Свон", slug: "ehinatseya-white-swan", category: "Квіти", price: 169, stock: 22, description: "Біла ехінацея з ніжними пелюстками та декоративною серединкою.", care: "Сонячна ділянка, дренований ґрунт, помірний полив.", seoTitle: "Ехінацея Вайт Свон", seoDescription: "Біла ехінацея Вайт Свон для садових композицій." },
  { name: "Гортензія метельчаста Ванілла Фрейз", slug: "hortenziya-vanilla-freize", category: "Квіти", price: 399, stock: 16, description: "Популярна гортензія з великими біло рожевими суцвіттями.", care: "Півтінь, вологий ґрунт, регулярний полив.", seoTitle: "Гортензія Ванілла Фрейз", seoDescription: "Купити гортензію Ванілла Фрейз для саду." },
  { name: "Гортензія Аннабель", slug: "hortenziya-annabel", category: "Квіти", price: 379, stock: 14, description: "Гортензія з великими кулястими білими суцвіттями.", care: "Півтінь, волога земля, весняна обрізка.", seoTitle: "Гортензія Аннабель", seoDescription: "Біла гортензія Аннабель для декоративного саду." },
  { name: "Ірис бородатий Блу Меджик", slug: "irys-borodatyi-blue-magic", category: "Квіти", price: 119, stock: 30, description: "Ефектний ірис із синьо фіолетовими квітами.", care: "Сонце, легкий ґрунт, помірний полив.", seoTitle: "Ірис Блу Меджик", seoDescription: "Купити бородатий ірис Блу Меджик." },
  { name: "Ірис бородатий Санрайз", slug: "irys-borodatyi-sunrise", category: "Квіти", price: 125, stock: 26, description: "Яскравий ірис теплих жовто помаранчевих відтінків.", care: "Сонячне місце, дренований ґрунт, без перезволоження.", seoTitle: "Ірис Санрайз", seoDescription: "Декоративний ірис Санрайз для клумб." },
  { name: "Лілія азійська Ред Твін", slug: "lyliya-azijska-red-twin", category: "Квіти", price: 99, stock: 44, description: "Яскрава азійська лілія з насиченим червоним цвітінням.", care: "Сонце, поживний ґрунт, регулярний полив.", seoTitle: "Лілія Ред Твін", seoDescription: "Купити азійську лілію Ред Твін." },
  { name: "Лілія біла Касабланка", slug: "lyliya-bila-casablanca", category: "Квіти", price: 129, stock: 32, description: "Вишукана біла лілія з великими ароматними квітами.", care: "Сонце або півтінь, родючий ґрунт, дренаж.", seoTitle: "Лілія Касабланка", seoDescription: "Біла лілія Касабланка для саду та зрізу." },
  { name: "Хоста Блу Ангел", slug: "hosta-blue-angel", category: "Квіти", price: 189, stock: 20, description: "Декоративна хоста з великим синювато зеленим листям.", care: "Півтінь або тінь, вологий ґрунт, мульчування.", seoTitle: "Хоста Блу Ангел", seoDescription: "Купити хосту Блу Ангел для тінистого саду." },
  { name: "Хоста Патріот", slug: "hosta-patriot", category: "Квіти", price: 179, stock: 21, description: "Хоста з контрастним зеленим листям і світлою облямівкою.", care: "Півтінь, регулярний полив, захист від спеки.", seoTitle: "Хоста Патріот", seoDescription: "Декоративна хоста Патріот для клумб." },
  { name: "Флокс метельчастий Брайт Айз", slug: "floks-bright-eyes", category: "Квіти", price: 145, stock: 27, description: "Ароматний флокс із ніжними рожевими квітами.", care: "Сонце, вологий ґрунт, підживлення в сезон.", seoTitle: "Флокс Брайт Айз", seoDescription: "Купити флокс Брайт Айз для саду." },
  { name: "Флокс Вайт Адмірал", slug: "floks-white-admiral", category: "Квіти", price: 145, stock: 23, description: "Білий багаторічний флокс для квітників і міксбордерів.", care: "Сонячне місце, помірний полив, обрізка після цвітіння.", seoTitle: "Флокс Вайт Адмірал", seoDescription: "Білий флокс Вайт Адмірал для декоративної посадки." },
  { name: "Рудбекія Голдштурм", slug: "rudbekiya-goldsturm", category: "Квіти", price: 155, stock: 31, description: "Сонячна багаторічна квітка з жовтими пелюстками.", care: "Сонце, невибагливий ґрунт, помірний полив.", seoTitle: "Рудбекія Голдштурм", seoDescription: "Купити рудбекію Голдштурм для яскравої клумби." },
  { name: "Дельфініум Блу Берд", slug: "delfinium-blue-bird", category: "Квіти", price: 199, stock: 17, description: "Висока квітка з великими синіми суцвіттями.", care: "Сонце, опора для стебел, регулярний полив.", seoTitle: "Дельфініум Блу Берд", seoDescription: "Синій дельфініум Блу Берд для саду." },
  { name: "Самшит вічнозелений", slug: "samshyt-vichnozelenyi", category: "Кущі", price: 249, stock: 25, description: "Компактний вічнозелений кущ для бордюрів і формування.", care: "Півтінь або сонце, регулярна стрижка, помірний полив.", seoTitle: "Самшит вічнозелений", seoDescription: "Купити самшит вічнозелений для живоплоту." },
  { name: "Барбарис Тунберга Атропурпуреа", slug: "barbarys-tunberga-atropurpurea", category: "Кущі", price: 279, stock: 18, description: "Декоративний кущ із темно пурпуровим листям.", care: "Сонячне місце, дренований ґрунт, обрізка навесні.", seoTitle: "Барбарис Атропурпуреа", seoDescription: "Барбарис Тунберга Атропурпуреа для саду." },
  { name: "Барбарис Голден Рокет", slug: "barbarys-golden-rocket", category: "Кущі", price: 289, stock: 16, description: "Вертикальний барбарис із яскравим жовтим листям.", care: "Сонце, помірний полив, формувальна обрізка.", seoTitle: "Барбарис Голден Рокет", seoDescription: "Купити жовтий барбарис Голден Рокет." },
  { name: "Спірея японська Голдфлейм", slug: "spireya-goldflame", category: "Кущі", price: 199, stock: 30, description: "Невисокий кущ із декоративним золотистим листям.", care: "Сонце, помірний полив, обрізка після цвітіння.", seoTitle: "Спірея Голдфлейм", seoDescription: "Спірея японська Голдфлейм для саду." },
  { name: "Спірея Грефшейм", slug: "spireya-grefsheim", category: "Кущі", price: 219, stock: 22, description: "Рясноквітучий кущ із білими весняними квітами.", care: "Сонце або півтінь, регулярний полив у спеку.", seoTitle: "Спірея Грефшейм", seoDescription: "Купити спірею Грефшейм для живоплоту." },
  { name: "Вейгела Ред Принц", slug: "veigela-red-prince", category: "Кущі", price: 299, stock: 15, description: "Декоративний кущ із яскравими червоними квітами.", care: "Сонце, родючий ґрунт, обрізка після цвітіння.", seoTitle: "Вейгела Ред Принц", seoDescription: "Купити вейгелу Ред Принц для саду." },
  { name: "Вейгела Варієгата", slug: "veigela-variegata", category: "Кущі", price: 309, stock: 14, description: "Кущ із рожевими квітами та строкатим листям.", care: "Сонце або півтінь, помірний полив, дренаж.", seoTitle: "Вейгела Варієгата", seoDescription: "Декоративна вейгела Варієгата для клумб." },
  { name: "Бузок Красуня Москви", slug: "buzok-krasunya-moskvy", category: "Кущі", price: 349, stock: 11, description: "Ароматний бузок із ніжними світлими суцвіттями.", care: "Сонце, родючий ґрунт, обрізка після цвітіння.", seoTitle: "Бузок Красуня Москви", seoDescription: "Купити бузок Красуня Москви для саду." },
  { name: "Бузок Сенсація", slug: "buzok-sensatsiya", category: "Кущі", price: 359, stock: 9, description: "Ефектний бузок із контрастними фіолетовими квітами.", care: "Сонячне місце, помірний полив, видалення відцвілих суцвіть.", seoTitle: "Бузок Сенсація", seoDescription: "Декоративний бузок Сенсація для саду." },
  { name: "Форзиція Лінвуд Голд", slug: "forzytsiya-lynwood-gold", category: "Кущі", price: 239, stock: 20, description: "Ранньоквітучий кущ із яскравими жовтими квітами.", care: "Сонце, невибагливий ґрунт, обрізка після цвітіння.", seoTitle: "Форзиція Лінвуд Голд", seoDescription: "Купити форзицію Лінвуд Голд для весняного саду." },
  { name: "Дерен білий Сібіріка", slug: "deren-bilyi-sibirica", category: "Кущі", price: 259, stock: 19, description: "Кущ із декоративними червоними пагонами та світлим листям.", care: "Сонце або півтінь, регулярна обрізка, вологий ґрунт.", seoTitle: "Дерен Сібіріка", seoDescription: "Декоративний дерен Сібіріка для саду." },
  { name: "Дерен Елегантіссіма", slug: "deren-elegantissima", category: "Кущі", price: 269, stock: 17, description: "Строкатий дерен із біло зеленим листям.", care: "Півтінь, помірний полив, формувальна обрізка.", seoTitle: "Дерен Елегантіссіма", seoDescription: "Купити дерен Елегантіссіма для ландшафту." },
  { name: "Пухироплідник Діаболо", slug: "puhyroplidnyk-diabolo", category: "Кущі", price: 289, stock: 18, description: "Декоративний кущ із темним бордовим листям.", care: "Сонце, невибагливий ґрунт, обрізка навесні.", seoTitle: "Пухироплідник Діаболо", seoDescription: "Пухироплідник Діаболо для контрастних посадок." },
  { name: "Пухироплідник Лютеус", slug: "puhyroplidnyk-luteus", category: "Кущі", price: 279, stock: 16, description: "Кущ із яскравим жовто зеленим листям.", care: "Сонце або півтінь, помірний полив, стрижка за потреби.", seoTitle: "Пухироплідник Лютеус", seoDescription: "Купити пухироплідник Лютеус для саду." },
  { name: "Ялівець Блу Стар", slug: "yalivets-blue-star", category: "Кущі", price: 399, stock: 13, description: "Компактний хвойний кущ із сріблясто блакитною хвоєю.", care: "Сонце, дренований ґрунт, мінімальний полив.", seoTitle: "Ялівець Блу Стар", seoDescription: "Купити ялівець Блу Стар для рокарію." },
  { name: "Ялівець Голд Стар", slug: "yalivets-gold-star", category: "Кущі", price: 389, stock: 12, description: "Низькорослий ялівець із золотистим відтінком хвої.", care: "Сонячна ділянка, легкий ґрунт, без застою води.", seoTitle: "Ялівець Голд Стар", seoDescription: "Декоративний ялівець Голд Стар для саду." },
  { name: "Туя Даніка", slug: "tuya-danika", category: "Кущі", price: 329, stock: 24, description: "Куляста компактна туя для бордюрів і контейнерів.", care: "Сонце або півтінь, регулярний полив після посадки.", seoTitle: "Туя Даніка", seoDescription: "Купити тую Даніка для декоративної посадки." },
  { name: "Туя Смарагд", slug: "tuya-smaragd", category: "Кущі", price: 459, stock: 20, description: "Вічнозелена туя з густою конічною кроною.", care: "Сонце, вологий ґрунт, полив у сухий період.", seoTitle: "Туя Смарагд", seoDescription: "Туя Смарагд для живоплоту та саду." },
  { name: "Кизильник горизонтальний", slug: "kyzylnyk-horyzontalnyi", category: "Кущі", price: 199, stock: 21, description: "Низький кущ із декоративними ягодами та дрібним листям.", care: "Сонце або півтінь, невибагливий догляд, обрізка за потреби.", seoTitle: "Кизильник горизонтальний", seoDescription: "Купити кизильник горизонтальний для схилів і бордюрів." },
  { name: "Жасмин садовий Сноубель", slug: "zhasmyn-sadovyi-snowbelle", category: "Кущі", price: 319, stock: 10, description: "Ароматний садовий жасмин із білими махровими квітами.", care: "Сонце або півтінь, помірний полив, обрізка після цвітіння.", seoTitle: "Жасмин Сноубель", seoDescription: "Купити садовий жасмин Сноубель." },
  { name: "М’ята перцева", slug: "myata-pertseva", category: "Трави", price: 79, stock: 50, description: "Ароматна м’ята для чаю, десертів і домашнього саду.", care: "Півтінь, регулярний полив, контроль розростання.", seoTitle: "М’ята перцева купити", seoDescription: "Купити м’яту перцеву для саду та горщика." },
  { name: "М’ята шоколадна", slug: "myata-shokoladna", category: "Трави", price: 89, stock: 42, description: "М’ята з приємним солодкуватим ароматом для напоїв.", care: "Півтінь, вологий ґрунт, обрізка молодих пагонів.", seoTitle: "М’ята шоколадна", seoDescription: "Ароматна шоколадна м’ята для вирощування вдома." },
  { name: "Базилік зелений", slug: "bazylik-zelenyi", category: "Трави", price: 69, stock: 60, description: "Класичний зелений базилік для салатів і соусів.", care: "Сонце, тепле місце, регулярний полив.", seoTitle: "Базилік зелений", seoDescription: "Купити зелений базилік для кухні та саду." },
  { name: "Базилік фіолетовий", slug: "bazylik-fioletovyi", category: "Трави", price: 75, stock: 55, description: "Ароматний фіолетовий базилік із декоративним листям.", care: "Сонце, поживний ґрунт, полив без перезволоження.", seoTitle: "Базилік фіолетовий", seoDescription: "Фіолетовий базилік для страв і декоративної грядки." },
  { name: "Розмарин лікарський", slug: "rozmaryn-likarskyi", category: "Трави", price: 119, stock: 35, description: "Ароматна середземноморська трава для кулінарії.", care: "Сонце, легкий ґрунт, помірний полив.", seoTitle: "Розмарин лікарський", seoDescription: "Купити розмарин лікарський у горщику." },
  { name: "Чебрець звичайний", slug: "chebrets-zvychainyi", category: "Трави", price: 85, stock: 48, description: "Невибаглива пряна трава з насиченим ароматом.", care: "Сонце, сухий ґрунт, мінімальний полив.", seoTitle: "Чебрець звичайний", seoDescription: "Чебрець для саду, чаю та кулінарії." },
  { name: "Чебрець лимонний", slug: "chebrets-lymonnyi", category: "Трави", price: 95, stock: 40, description: "Ароматний чебрець із легкими лимонними нотами.", care: "Сонце, дренований ґрунт, помірний полив.", seoTitle: "Чебрець лимонний", seoDescription: "Купити лимонний чебрець для саду." },
  { name: "Орегано грецьке", slug: "oregano-gretske", category: "Трави", price: 89, stock: 44, description: "Пряна трава з сильним ароматом для середземноморських страв.", care: "Сонце, легкий ґрунт, обрізка для кущіння.", seoTitle: "Орегано грецьке", seoDescription: "Купити грецьке орегано для кулінарії." },
  { name: "Шавлія лікарська", slug: "shavliya-likarska", category: "Трави", price: 99, stock: 38, description: "Декоративна і корисна трава із сіруватим листям.", care: "Сонце, сухий ґрунт, помірний полив.", seoTitle: "Шавлія лікарська", seoDescription: "Шавлія лікарська для саду та кухні." },
  { name: "Петрушка кучерява", slug: "petrushka-kucheryava", category: "Трави", price: 49, stock: 70, description: "Популярна зелень із декоративним кучерявим листям.", care: "Сонце або півтінь, регулярний полив.", seoTitle: "Петрушка кучерява", seoDescription: "Купити кучеряву петрушку для грядки." },
  { name: "Петрушка листова", slug: "petrushka-lystova", category: "Трави", price: 45, stock: 75, description: "Ароматна листова петрушка для щоденного використання.", care: "Півтінь, вологий ґрунт, регулярний зріз листя.", seoTitle: "Петрушка листова", seoDescription: "Листова петрушка для вирощування вдома." },
  { name: "Кріп ароматний", slug: "krip-aromatnyi", category: "Трави", price: 39, stock: 80, description: "Класичний ароматний кріп для салатів і консервації.", care: "Сонце, пухкий ґрунт, регулярний посів.", seoTitle: "Кріп ароматний", seoDescription: "Купити кріп ароматний для грядки." },
  { name: "Кінза свіжа", slug: "kinza-svizha", category: "Трави", price: 55, stock: 58, description: "Пряна зелень із характерним ароматом для страв.", care: "Сонце або півтінь, регулярний полив, швидкий збір.", seoTitle: "Кінза свіжа", seoDescription: "Кінза для вирощування в саду та горщику." },
  { name: "Естрагон французький", slug: "estragon-frantsuzkyi", category: "Трави", price: 109, stock: 28, description: "Ароматна багаторічна трава для соусів і маринадів.", care: "Сонце, помірний полив, обрізка пагонів.", seoTitle: "Естрагон французький", seoDescription: "Купити французький естрагон для кулінарії." },
  { name: "Меліса лимонна", slug: "melisa-lymonna", category: "Трави", price: 79, stock: 46, description: "Ніжна ароматна трава з лимонним запахом для чаю.", care: "Півтінь, вологий ґрунт, регулярна обрізка.", seoTitle: "Меліса лимонна", seoDescription: "Купити лимонну мелісу для чаю." },
  { name: "Лемонграс", slug: "lemongras", category: "Трави", price: 129, stock: 25, description: "Теплолюбна ароматна трава з яскравим цитрусовим ароматом.", care: "Сонце, тепло, регулярний полив без застою води.", seoTitle: "Лемонграс купити", seoDescription: "Лемонграс для чаю, кухні та вирощування в горщику." },
  { name: "Рукола садова", slug: "rukola-sadova", category: "Трави", price: 59, stock: 66, description: "Швидкоросла зелень із пікантним смаком для салатів.", care: "Сонце або півтінь, регулярний полив, частий зріз.", seoTitle: "Рукола садова", seoDescription: "Купити руколу садову для домашньої грядки." },
  { name: "Щавель зелений", slug: "shchavel-zelenyi", category: "Трави", price: 65, stock: 39, description: "Багаторічна зелень із кислуватим смаком для супів і салатів.", care: "Півтінь, вологий ґрунт, регулярний збір листя.", seoTitle: "Щавель зелений", seoDescription: "Зелений щавель для саду та кухні." },
  { name: "Фенхель овочевий", slug: "fenhel-ovochevyi", category: "Трави", price: 95, stock: 33, description: "Ароматна рослина з ніжним смаком для салатів і страв.", care: "Сонце, родючий ґрунт, регулярний полив.", seoTitle: "Фенхель овочевий", seoDescription: "Купити овочевий фенхель для вирощування." },
  { name: "Любисток лікарський", slug: "lyubystok-likarskyi", category: "Трави", price: 89, stock: 37, description: "Багаторічна пряна трава з насиченим ароматом.", care: "Сонце або півтінь, вологий ґрунт, обрізка пагонів.", seoTitle: "Любисток лікарський", seoDescription: "Любисток лікарський для саду та кулінарії." },
];

export const REMOVED_DEMO_PRODUCT_SLUGS = ["petuniya-miks", "pomidor-cherry"] as const;

export const CATEGORY_SLUG_BY_LABEL: Record<SeedProductRow["category"], string> = {
  Квіти: "kvity",
  Кущі: "dekoratyvni-kushi",
  Трави: "dekoratyvni-travy",
};

export function seedProductImageUrl(slug: string): string {
  return `https://placehold.co/600x600/e8f4f0/5C97A8/png?text=${encodeURIComponent(slug.slice(0, 24))}`;
}
